import React, { useState, useEffect } from "react";
import { Sidebar } from "./components/layout/Sidebar";
import { Topbar } from "./components/layout/Topbar";
import { NotificationToast } from "./components/layout/NotificationToast";

// Modules
import { DashboardModule } from "./components/modules/DashboardModule";
import { NewProjectModule } from "./components/modules/NewProjectModule";
import { StoryGeneratorModule } from "./components/modules/StoryGeneratorModule";
import { CharacterProfileModule } from "./components/modules/CharacterProfileModule";
import { SceneBuilderModule } from "./components/modules/SceneBuilderModule";
import { ImagePromptsModule } from "./components/modules/ImagePromptsModule";
import { VoiceModule } from "./components/modules/VoiceModule";
import { MusicModule } from "./components/modules/MusicModule";
import { VideoPromptsModule } from "./components/modules/VideoPromptsModule";
import { StoryboardModule } from "./components/modules/StoryboardModule";
import { ConsistencyModule } from "./components/modules/ConsistencyModule";
import { ProjectsModule } from "./components/modules/ProjectsModule";
import { SettingsModule } from "./components/modules/SettingsModule";
import { ExportModal } from "./components/modules/ExportModal";

// Services
import { storageService } from "./services/storageService";

export default function App() {
  const [activeTab, setActiveTab] = useState("dashboard");
  const [projects, setProjects] = useState(() => storageService.getProjects());
  const [activeProject, setActiveProject] = useState(() => storageService.getActiveProject());

  // Modals & UI States
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [isExportModalOpen, setIsExportModalOpen] = useState(false);
  const [toast, setToast] = useState(null);

  // Auto-hide toast after 3 seconds
  useEffect(() => {
    if (toast) {
      const timer = setTimeout(() => setToast(null), 3200);
      return () => clearTimeout(timer);
    }
  }, [toast]);

  const showToast = (message, type = "success") => {
    setToast({ message, type });
  };

  // Update Project handler
  const handleUpdateProject = (updatedProject) => {
    const saved = storageService.saveProject(updatedProject);
    setActiveProject(saved);
    setProjects(storageService.getProjects());
  };

  // Select project by ID
  const handleSelectProject = (projectId) => {
    storageService.setActiveProjectId(projectId);
    const proj = storageService.getActiveProject();
    setActiveProject(proj);
    showToast(`Projek '${proj.name}' diaktifkan!`, "info");
  };

  // Duplicate project
  const handleDuplicateProject = (projectId) => {
    const duplicated = storageService.duplicateProject(projectId);
    if (duplicated) {
      setProjects(storageService.getProjects());
      setActiveProject(duplicated);
      showToast(`Projek berjaya disalin: ${duplicated.name}`, "success");
    }
  };

  // Delete project
  const handleDeleteProject = (projectId) => {
    const confirmDelete = window.confirm("Adakah anda pasti ingin memadam projek ini?");
    if (!confirmDelete) return;

    storageService.deleteProject(projectId);
    const remaining = storageService.getProjects();
    setProjects(remaining);
    setActiveProject(storageService.getActiveProject());
    showToast("Projek berjaya dipadam.", "info");
  };

  // Reset to default sample project
  const handleResetSample = () => {
    const sample = storageService.resetSample();
    setProjects([sample]);
    setActiveProject(sample);
    showToast("Sampel 'Warisan Ukiran' berjaya dimuat semula!", "success");
  };

  // Callback when a brand new project is generated by NewProjectModule
  const handleProjectCreated = (newProject) => {
    const saved = storageService.saveProject(newProject);
    setProjects(storageService.getProjects());
    setActiveProject(saved);
    showToast(`Projek '${newProject.name}' berjaya dijana dengan AI!`, "success");
  };

  // Render module based on activeTab
  const renderActiveModule = () => {
    switch (activeTab) {
      case "dashboard":
        return (
          <DashboardModule
            project={activeProject}
            projects={projects}
            onNavigate={setActiveTab}
            onSelectProject={handleSelectProject}
            onResetSample={handleResetSample}
          />
        );
      case "new-project":
        return (
          <NewProjectModule
            onProjectCreated={handleProjectCreated}
            onNavigate={setActiveTab}
          />
        );
      case "story":
        return (
          <StoryGeneratorModule
            project={activeProject}
            onUpdateProject={handleUpdateProject}
            showToast={showToast}
          />
        );
      case "character-profile":
        return (
          <CharacterProfileModule
            project={activeProject}
            onUpdateProject={handleUpdateProject}
            showToast={showToast}
          />
        );
      case "scene-builder":
        return (
          <SceneBuilderModule
            project={activeProject}
            onUpdateProject={handleUpdateProject}
            showToast={showToast}
          />
        );
      case "image-prompts":
        return (
          <ImagePromptsModule
            project={activeProject}
            onUpdateProject={handleUpdateProject}
            showToast={showToast}
          />
        );
      case "voice":
        return (
          <VoiceModule
            project={activeProject}
            onUpdateProject={handleUpdateProject}
            showToast={showToast}
          />
        );
      case "music":
        return (
          <MusicModule
            project={activeProject}
            onUpdateProject={handleUpdateProject}
            showToast={showToast}
          />
        );
      case "video-prompts":
        return (
          <VideoPromptsModule
            project={activeProject}
            onUpdateProject={handleUpdateProject}
            showToast={showToast}
          />
        );
      case "storyboard":
        return (
          <StoryboardModule
            project={activeProject}
            onUpdateProject={handleUpdateProject}
            showToast={showToast}
          />
        );
      case "consistency":
        return (
          <ConsistencyModule
            project={activeProject}
            onUpdateProject={handleUpdateProject}
            showToast={showToast}
          />
        );
      case "projects":
        return (
          <ProjectsModule
            project={activeProject}
            projects={projects}
            onSelectProject={handleSelectProject}
            onDuplicateProject={handleDuplicateProject}
            onDeleteProject={handleDeleteProject}
            onResetSample={handleResetSample}
            onNavigate={setActiveTab}
            onOpenExportModal={() => setIsExportModalOpen(true)}
          />
        );
      case "settings":
        return <SettingsModule showToast={showToast} />;
      default:
        return (
          <DashboardModule
            project={activeProject}
            projects={projects}
            onNavigate={setActiveTab}
            onSelectProject={handleSelectProject}
            onResetSample={handleResetSample}
          />
        );
    }
  };

  return (
    <div className="app-layout">
      {/* 12-Item Sidebar Navigation */}
      <Sidebar
        activeTab={activeTab}
        onSelectTab={setActiveTab}
        isOpen={isMobileMenuOpen}
        onClose={() => setIsMobileMenuOpen(false)}
      />

      {/* Main Studio Canvas */}
      <div className="main-wrapper">
        {/* Topbar Header */}
        <Topbar
          project={activeProject}
          onOpenMobileMenu={() => setIsMobileMenuOpen(true)}
          onOpenConsistencyModal={() => setActiveTab("consistency")}
          onOpenExportModal={() => setIsExportModalOpen(true)}
          onNewProjectClick={() => setActiveTab("new-project")}
        />

        {/* Dynamic Module Body */}
        <main className="main-content">
          {renderActiveModule()}
        </main>
      </div>

      {/* Export Modal */}
      <ExportModal
        isOpen={isExportModalOpen}
        onClose={() => setIsExportModalOpen(false)}
        project={activeProject}
        showToast={showToast}
      />

      {/* Global Notification Toast */}
      <NotificationToast
        toast={toast}
        onClose={() => setToast(null)}
      />
    </div>
  );
}
